--1.
SELECT FIRST_NAME ||''||  LAST_NAME AS FULL_NAME 
FROM EMPLOYEES;

--2.
SELECT FULL NAME, SAL, DEPARTMENT_NO
FROM EMPLOYEES
WHERE (department_id = 30 AND SAL <10000);

--3.
SELECT FULL_NAME
FROM  EMPLOYEES
WHERE (DEPARTMENT_ID =);
